"""Add copilot_action_proposals table

Revision ID: a65158de7a77
Revises: 20260801_01
Create Date: 2026-08-02 18:02:17.755515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a65158de7a77'
down_revision = '20260801_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_action_proposals',
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_action_proposals_organization_id'), 'copilot_action_proposals', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_balances_organization_id'), 'inventory_balances', ['organization_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_organization_id'), 'inventory_locations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_product_categories_organization_id'), 'product_categories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index('ix_movement_org_product_time', 'stock_movements', ['organization_id', 'product_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_organization_id'), 'stock_movements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_index(op.f('ix_stock_movements_organization_id'), table_name='stock_movements')
    op.drop_index('ix_movement_org_product_time', table_name='stock_movements')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index(op.f('ix_product_categories_organization_id'), table_name='product_categories')
    op.drop_index(op.f('ix_inventory_locations_organization_id'), table_name='inventory_locations')
    op.drop_index(op.f('ix_inventory_balances_organization_id'), table_name='inventory_balances')
    op.drop_index(op.f('ix_copilot_action_proposals_organization_id'), table_name='copilot_action_proposals')
    op.drop_table('copilot_action_proposals')
    # ### end Alembic commands ###
