"""Add CopilotConversationMessage

Revision ID: bb3d9584e6c6
Revises: a65158de7a77
Create Date: 2026-08-02 22:29:11.913303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3d9584e6c6'
down_revision = 'a65158de7a77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_conversation_messages',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_conversation_messages_organization_id'), 'copilot_conversation_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_copilot_conversation_messages_user_id'), 'copilot_conversation_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_conversation_messages_user_id'), table_name='copilot_conversation_messages')
    op.drop_index(op.f('ix_copilot_conversation_messages_organization_id'), table_name='copilot_conversation_messages')
    op.drop_table('copilot_conversation_messages')
    # ### end Alembic commands ###
